#!/bin/bash
awk 'BEGIN{FS=""
	   l["a"]=0;l["b"]=0;l["c"]=0;l["d"]=0;l["e"]=0;l["f"]=0;l["g"]=0
	   l["h"]=0;l["i"]=0;l["j"]=0;l["k"]=0;l["l"]=0;l["m"]=0;l["n"]=0
	   l["o"]=0;l["p"]=0;l["q"]=0;l["r"]=0;l["s"]=0;l["t"]=0;l["u"]=0
	   l["v"]=0;l["w"]=0;l["x"]=0;l["y"]=0;l["z"]=0
          }
     {for(i=1;i<=NF;i++) {

      }}
     END{ for( in l) {
           printf "%s %.3f\n",letter,(l[letter]/total)*100
          }}' ${1} | sort