#!/bin/bash
MAX=100
PERC_PER=14
ENGLISH_FREQ=( $(awk '{print $2}' english_frequency.data) )
INPUT_FREQ=( $(awk '{print $2}' ${1}) )
LETTERS=( $(awk '{print $1}' english_frequency.data) )
printf " |%s%i\n" $(perl -e 'print "-"x80') 14
for((i=0;i<${#ENGLISH_FREQ[@]};i++))
do
    X=${ENGLISH_FREQ[${i}]}
    Y=${INPUT_FREQ[${i}]}
    LETTER=${LETTERS[${i}]}
    ENGLISH_STAPLE=$(perl -e "print \"e\" x (${X}/${PERC_PER}*80)")
    INPUT_STAPLE=$(perl -e "print \"/\" x (${Y}/${PERC_PER}*80)")
    printf "%s|%s\n" ${LETTER} ${ENGLISH_STAPLE}
    printf " |%s\n"  ${INPUT_STAPLE}
done