#!/bin/bash
N=1
LETTERS=("a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s" "t" "u" "v" "w" "x" "y" "z")
for ROW in $(bash columns_to_rows ${1})
do 
    printf "Row ${N} "
    BEST_KEY=0
    BEST_DIST=$(bash caesar 1 ${ROW} | bash letter_frequency | bash distance_from_english)
    for KEY in {1..25}
    do
	RES=$(bash caesar ${KEY} ${ROW} | bash letter_frequency | bash distance_from_english)
	if [[ ${RES} < ${BEST_DIST} ]]
	then
	    BEST_KEY=${KEY}
	    BEST_DIST=${RES}
	fi
    done
    printf "%2s %2s %2f\n" ${BEST_KEY} ${LETTERS[${BEST_KEY}]} ${BEST_DIST}
    N=$((N+1))
done