#!/bin/bash
FILE=$(mktemp)
for i in {3..6}
do 
    for PIECE in $(grep -oE "\w{${i}}" cipher.txt | sort | uniq)
    do       
 	HITS=$(grep -ob ${PIECE} cipher.txt)
 	echo ${PIECE} ${HITS} | awk 'NF>2' | tr ' ' ':' | awk 'BEGIN{FS=":"}{print $4-$2}' >> ${FILE}
    done
done
awk 'BEGIN { printf "%5s %5s\n","distance","repetitions"} 
     { for(i=1;i<=NF;i++) {
          nums[$i]++
       }
     }
     END{ for(n in nums) {
            printf "%5i %5i\n",n,nums[n]
          }
        }' ${FILE}
rm ${FILE}